# Generated by Django 4.2 on 2025-02-03 17:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(max_length=100)),
                ('correu', models.CharField(max_length=100)),
                ('curs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('rol', models.CharField(max_length=100)),
                ('moduls', models.CharField(max_length=100)),
            ],
        ),
    ]
