version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db_django
    environment:
      - POSTGRES_DB=ITIC_DB
      - POSTGRES_PASSWORD=ITIC
      - POSTGRES_USER=ITIC_user
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin5
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_milena.vardumyan@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: milena123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
